<a href="https://colab.research.google.com/github/srikharshashi/learn-dl/blob/main/tensors_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [36]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [35]:
!nvidia-smi

Fri Apr  7 16:13:46 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0    33W /  70W |    567MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Create tensors with tf.constant() -- immutable


In [ ]:
scalar=tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

# Check dimensions

In [ ]:
scalar.ndim

0

## Create a vector


In [ ]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

##  Create a matrix (has more than 1 dimension)

In [ ]:
matrix=tf.constant([[10,7 ],[10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [ ]:
matrix.ndim


2

Tensors created with t.Variable() are tensors which can be modified using.assign()

**Creating Random Tensors**

In [ ]:
random_l=tf.random.Generator.from_seed(42) 
random_l=random_l.normal(shape=(3,2))
random_l

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### Shuffle order of elements in a tensor 


In [ ]:
# tf.andom.shuffle shuffles the tensor in one dimension
un_shuffled=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(un_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

## Numpy arrays into tensors

In [ ]:
arr=np.array([1,2,3,4,5])
tf.convert_to_tensor(arr)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

## Tensor Attributes
- Shape
- Rank 
- Size 
- Dimension

Tensors are index like normal arrays and can be accesed like tf[0]

In [ ]:
rank4_tensor=tf.zeros(shape=(2,3,4,5))
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

## Indexing and expanding tensors

Indexes are something like this [start(inclusive):end(exclusive)]

In [ ]:
#Getting first 2 elements in each dimension
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
 t1=tf.zeros(shape=(2,3,3,))

In [ ]:
t1

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
t1+10

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]], dtype=float32)>

In [ ]:
t2=t1+1
    


In [ ]:
t2

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
t2 * (t1+10)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]], dtype=float32)>

In [ ]:
t1 @ t2

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
t1

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

Matrix multiplication 

- `tf.matmul()`
- `tf.tensordot()`

In [ ]:
X=tf.random.uniform((2,3))
Y=tf.random.uniform((3,2))

In [ ]:
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.3652948 , 0.41193402, 0.7851713 ],
       [0.5355004 , 0.35189342, 0.67423105]], dtype=float32)>

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.81353295, 0.9590894 ],
       [0.39782703, 0.05097759],
       [0.8851758 , 0.11821222]], dtype=float32)>

In [ ]:
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.1560725 , 0.46416664],
       [1.1724529 , 0.61123383]], dtype=float32)>

In [ ]:
tf.matmul(X,Y)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.1560725 , 0.46416664],
       [1.1724529 , 0.61123383]], dtype=float32)>

In [ ]:
Z=tf.random.uniform((3,2))

In [ ]:
X * tf.transpose(Z)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.25809675, 0.03724109, 0.6152968 ],
       [0.43620828, 0.11642625, 0.40253854]], dtype=float32)>

In [ ]:
Z* tf.reshape(X,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.25809675, 0.3355535 ],
       [0.07098377, 0.17717382],
       [0.27576008, 0.40253854]], dtype=float32)>

Type Casting


In [ ]:
tf.cast(X,dtype=tf.float16)

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[0.3652, 0.4119, 0.785 ],
       [0.5356, 0.3518, 0.6743]], dtype=float16)>

**Aggregating Tensors**

In [ ]:
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([83, 69, 80, 40, 93, 48, 22,  9, 15, 83, 95, 95, 34, 32, 68, 49, 71,
       18, 43, 56, 34, 14, 87, 69, 29, 57, 38, 46, 54, 25, 47, 99, 92, 78,
       13, 22, 85, 96,  3, 54, 85, 55, 99, 28,  7, 79, 32, 17, 56, 90])>

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [23]:
G=tf.constant(np.random.randint(0,100,size=(1,1,1,50)))


In [24]:
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=int64, numpy=
array([[[[39,  4, 34, 70, 39, 55, 25, 31,  3, 24, 46, 47, 57, 92, 68,
          78, 93, 93, 45, 78, 78, 21, 59, 54, 11, 79, 93, 88, 43, 47,
          26, 68, 72, 76, 44, 51, 42, 63, 64, 43, 51, 76, 37, 55, 53,
          42,  8, 64, 49, 58]]]])>

In [26]:
# Remove all the extra dimensions in the 
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([39,  4, 34, 70, 39, 55, 25, 31,  3, 24, 46, 47, 57, 92, 68, 78, 93,
       93, 45, 78, 78, 21, 59, 54, 11, 79, 93, 88, 43, 47, 26, 68, 72, 76,
       44, 51, 42, 63, 64, 43, 51, 76, 37, 55, 53, 42,  8, 64, 49, 58])>

One Hot Encoding


In [29]:
li=[0,1,2,3]
tf.one_hot(li,depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

Tensor Flow and Numpy are interoperable 
 - Tho the default types of each are different 
 - int 64 if you cretae a tensor from np array
 - int 32 if you create a tensor from scratch

In [30]:
H=tf.random.uniform((3,3))
H1=np.array(H)
type(H1)

numpy.ndarray

In [33]:
H2=np.ones((3,3))
HT2=tf.Variable(H2)
type(HT2)

tensorflow.python.ops.resource_variable_ops.ResourceVariable